dependencies:
    - python=3.7
    - pip
    - numpy
    - scipy
    - pandas
    - jupyter
    - scikit-learn
    - pip:
          - watermark
          - pytest
          - scikit-surprise
          - google-cloud-bigquery
          - pandas-gbq
          - tqdm
